language: java
jdk:
 - oraclejdk8
notifications:
 email:
  recipients:
   - guiganister@gmail.com
  on_success: always
before_install:
- cd binary
- bash gitconfiguration.sh
- cd ..
- cd shelltests
- git config --global user.email "dfm2@cin.ufpe.br"
- git config --global user.name "Daniel Maida" 
- sudo apt-get install shunit2
script:
- cd shelltests
- shunit2 s3mGitTests.sh
- cd ..
